inflation_layer:
  enabled: true
  inflation_radius: 0.55
  cost_scaling_factor: 10

pointcloud_layer:
  enabled: true
  max_obstacle_height: 0.60  
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 10
  obstacle_range: 3.0
  raytrace_range: 3.0
  publish_voxel_map: false
  observation_sources: scan
  footprint_clearing_enabled: true
  scan: 
    data_type: LaserScan
    topic: /scan
    sensor_frame: laser
    marking: true
    clearing: true
    min_obstacle_height: 0.05
    max_obstacle_height: 0.6

global_frame: map
robot_base_frame: base_link
update_frequency: 12.0
publish_frequency: 12.0
transform_tolerance: 0.5
rolling_window: true
width: 2.5
height: 2.5
resolution: 0.2
footprint: [[0.42, 0.1243], [0.42, -0.1243], [-0.147, -0.1243], [-0.147, 0.1243]]
plugins:    
    - {name: pointcloud_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}

